theme: jekyll-theme-cayman

# Site settings
name: Ingo Griebsch
description: "Coding Architect @gbtec-ag | Husband and father | Boardgame addict | Loves Clutch as well as Tricky"
url: "https://www.ingogriebsch.de"
email: ingo.griebsch@gmx.de

github_username:  ingogriebsch
twitter_username: d0gb0t666
linkedin_username: benediktritter

avatar: yes
avatar_img_path: "https://avatars0.githubusercontent.com/u/18695610?s=460&v=4"

front_img: yes
front_img_path: "images/background.jpg"

# Build settings
markdown: kramdown
permalink: pretty
